name: C++ CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install GCC 13 and CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo apt-get update
        sudo apt-get install -y gcc-13 g++-13 cmake
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100
    
    - name: Cache CMake build and compiler info
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache
          build/CMakeCache.txt
          build/CMakeFiles
        key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-cmake-

    - name: Configure
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Run all tests
      run: ./build/cpp_tests