name: C++ CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake

    - name: Configure
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Run all tests
      run: |
        ./build/test_binary_search